# Generated by Django 2.1.15 on 2020-12-20 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DotaMatch',
            fields=[
                ('match_id', models.IntegerField(db_column='match_ID', primary_key=True, serialize=False)),
                ('match_status', models.CharField(db_column='match_Status', max_length=15)),
                ('match_duration', models.CharField(db_column='match_Duration', max_length=50)),
            ],
            options={
                'db_table': 'dota_match',
            },
        ),
        migrations.CreateModel(
            name='DotaPremiumuser',
            fields=[
                ('premiumuser_registration_number', models.BigIntegerField(db_column='premiumuser_Registration_Number', primary_key=True, serialize=False)),
                ('premiumuser_registrationexpirydate', models.CharField(db_column='premiumuser_RegistrationExpiryDate', max_length=30)),
            ],
            options={
                'db_table': 'dota_premiumuser',
            },
        ),
        migrations.CreateModel(
            name='DotaTournament',
            fields=[
                ('tournament_id', models.IntegerField(db_column='Tournament_ID', primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(db_column='Tournament_name', max_length=100)),
                ('tournament_starting_timedate', models.DateTimeField(db_column='Tournament_starting_timedate')),
                ('tournament_end_timedate', models.DateTimeField(db_column='Tournament_end_timedate')),
                ('tournament_prize', models.CharField(db_column='Tournament_prize', max_length=100)),
            ],
            options={
                'db_table': 'dota_tournament',
            },
        ),
        migrations.CreateModel(
            name='DotaUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=45)),
                ('user_email', models.CharField(max_length=45)),
                ('user_username', models.CharField(max_length=30, unique=True)),
                ('user_password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'dota_user',
            },
        ),
        migrations.CreateModel(
            name='DotaAdmin',
            fields=[
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DotaSite.DotaUser')),
                ('admin_registration_number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'dota_admin',
            },
        ),
        migrations.CreateModel(
            name='DotaGamer',
            fields=[
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DotaSite.DotaUser')),
                ('gamer_ign', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'dota_gamer',
            },
        ),
        migrations.CreateModel(
            name='DotaGamerMatch',
            fields=[
                ('matchid', models.ForeignKey(db_column='matchid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DotaSite.DotaMatch')),
                ('match_gpm', models.IntegerField(db_column='match_GPM')),
                ('match_kills', models.IntegerField(db_column='match_Kills')),
                ('match_xpm', models.IntegerField(db_column='match_XPM')),
                ('match_death', models.IntegerField()),
                ('match_assist', models.IntegerField()),
            ],
            options={
                'db_table': 'dota_gamer_match',
            },
        ),
        migrations.CreateModel(
            name='DotaTournamentMatch',
            fields=[
                ('matchid', models.ForeignKey(db_column='Matchid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DotaSite.DotaMatch')),
                ('tournamentid', models.ForeignKey(db_column='Tournamentid', on_delete=django.db.models.deletion.DO_NOTHING, to='DotaSite.DotaTournament')),
            ],
            options={
                'db_table': 'dota_tournament_match',
            },
        ),
        migrations.CreateModel(
            name='DotaMmr',
            fields=[
                ('mmr', models.ForeignKey(db_column='mmr_Id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DotaSite.DotaGamer')),
                ('mmr_score', models.BigIntegerField()),
                ('mmr_medal', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'dota_mmr',
            },
        ),
        migrations.AddField(
            model_name='dotapremiumuser',
            name='premiumuser_gamer',
            field=models.ForeignKey(db_column='premiumuser_Gamer_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='DotaSite.DotaGamer'),
        ),
        migrations.AddField(
            model_name='dotagamermatch',
            name='gamerid',
            field=models.ForeignKey(db_column='gamerid', on_delete=django.db.models.deletion.DO_NOTHING, to='DotaSite.DotaGamer'),
        ),
    ]
