# Generated by Django 2.1.15 on 2020-12-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DotaSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DotaAdmin',
            fields=[
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='DotaSite.DotaUser')),
                ('admin_registration_number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'dota_admin',
                'managed': False,
            },
        ),
    ]
