# Generated by Django 2.1.15 on 2021-01-13 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DotaSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotapremiumuser',
            name='premiumuser_gamer',
            field=models.ForeignKey(db_column='premiumuser_Gamer_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='DotaSite.AuthUser'),
        ),
    ]
